package ir.zhiran2021.snamall.utils

const val TYPE_ONE = "1"
const val TYPE_TWO = "2"
const val CHART = "chart"
const val COMPARE = "compare"
const val PRODUCT_ID = "id"
const val ID_ONE = "id_one"
const val ID_TWO = "id_two"
const val YES = "yes"
const val NO = "no"
const val WALLET = "wallet"
const val DIRECT = "direct"
const val ADDRESS_ID = "address_id"
const val REF_ID = "ref_id"
